# Configuration file for VoteLinks
# announcement-delay is calculated in seconds, not minutes
# You can add and remove links as you'd like, but keeping under 10 links is ideal if you'd like to fit it on the chat window all at once
# If you need help don't hesitate to comment on the project page asking for it
# And seriously, don't change dont-ever-change-this as it will wipe your configuration
dont-ever-change-this: 2
announcements: true
announcement-delay: 900
announcement-message: '&aRemember to vote for us every day using /vote!'
links:
    - '&6Thanks for voting!'
    - '&bAdd a link here'
    - '&2Add a link here'
    - '&cAdd a link here'
    - '&dAdd a link here'