name: VotingLinks
main: me.tehkitti.VotingLinks.Main
version: 2.1.0
author: TehKitti
commands:
    vlabout:
        description: Shows information about the VotingLinks plugin.
        usage: /vlabout
    vote:
        description: Shows voting links.
        usage: /vote
permissions:
    votinglinks.vote:
        description: Lets you vote, granted by default to everybody.
        default: true
    votinglinks.about:
        description: Lets you see plugin information
        default: op