name: VotingLinks
main: com.vauff.votinglinks.core.Main
version: 3.0
author: Vauff
commands:
    vlabout:
        description: Shows you plugin information
        usage: /vlabout
    vote:
        description: Shows you voting links
        usage: /vote
    vlreload:
        description: Reloads the configuration file
        usage: /vlreload
permissions:
    votinglinks.vote:
        description: Gives permission to the /vote command and vote signs, both show you voting links
        default: true
    votinglinks.about:
        description: Gives permission to the /vlabout command, shows you plugin information
        default: true
    votinglinks.reload:
        description: Gives permission to the /vlreload command, reloads the configuration file
        default: op